# Generated by Django 5.2 on 2026-02-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('unidadeMedidaId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.unidademedida')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('ano', models.IntegerField(max_length=4)),
                ('horimetro', models.IntegerField(max_length=4)),
                ('marcaId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.marca')),
                ('modeloId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicaoId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.medicao')),
                ('veiculoId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.veiculo')),
            ],
        ),
    ]
